version: '2.3'

services:
  deluge:
    image: linuxserver/deluge:latest
    hostname: deluge
    container_name: deluge
    restart: unless-stopped
    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST5EDT
      - UMASK_SET=022

    volumes:
      - config:/config
      - downloads:/downloads
      - watch:/watch

    ports:
      - 8112:8112

volumes:
  config:
    driver: local
    driver_opts: 
      type: nfs
      o: "addr=172.16.1.10,nfsvers=4,rw"
      device: ":/mnt/luke/deluge/config"

  downloads:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.16.1.10,nfsvers=4,rw"
      device: ":/mnt/luke/deluge/downloads"

  watch:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.16.1.10,nfsvers=4,rw"
      device: ":/mnt/luke/deluge/watch"
